vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set backspace=indent,eol,start")
vim.cmd("set showcmd")
vim.cmd("set ruler")
vim.cmd("set showmatch")
vim.cmd("set laststatus=2")
vim.cmd("set mouse=a")
vim.cmd("set numberwidth=1")
vim.g.mapleader= " "