# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/cryptpart";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."cryptpart".device = "/dev/disk/by-uuid/c4237029-713f-4ec5-bf07-7ff814bda610";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2A31-4FE8";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8434500a-173e-4058-8b3f-a48358a6afe7"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
