# 1. Font Configuration
font_family      ComicShannsMono Nerd Font
bold_font        ComicShannsMono Nerd Font Bold
font_size        11.0
italic_font      auto
bold_italic_font auto

# Modify how Kitty blends text pixels (Reduces thickness)
#text_composition_strategy 1.0 0

# 2. Cursor Style
cursor_shape     beam
cursor_blink_interval 0.5

# 3. Window Background and Opacity
background       #070012
background_opacity 0.75

window_padding_width 10